discord:
  token: Njk5NDIxMTU2NTI4MjI2MzE2.G3G8wS.9uJrUBCkbVlMueFRhjgH2IO2rbSnk3TYZfPCj8
spring:
  datasource:
    url: jdbc:mysql://bd3eb3f262042c:8015d842@us-cdbr-east-05.cleardb.net/heroku_1145bb70a966eb6?reconnect=true
    username: root
    password: shizuka
server:
  port: ${PORT:8080}